apiVersion: v1
kind: Pod
metadata:
  name: gpu-web
  labels:
    app: web
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
  nodeSelector:
    hardware: local_gpus
