apiVersion: v1
kind: Pod
metadata:
  name: app-with-init
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  initContainers:
    - name: init-script
      image: busybox
      command: ['sh', '-c', 'echo Hello from Init Container > /data/init.txt']
      volumeMounts:
        - name: shared-data
          mountPath: /data
  containers:
    - name: main-app
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html